### PR TITLE
Integration3 saved recipes third party

### PR DESCRIPTION
**Pull request by nala-he**
User can search the third party recipe using recipe search side bar and save the recipe after viewing the recipe details. They will be directed to saved recipes page after clicking save recipes button. 

Save recipes page will show the saved local recipes count and saved spoonacular recipes count. The spoonacular recipes all have the green API logo as the avatar to differentiate with recipes in our own database.

Profile page's saved recipes count is also updated with the total number of saved local recipes and spoonacular recipes. 

Two issues: 
1. I have to comment out direction-list in recipe-details/Spoonacular-Recipe-Detail to make the spoonacular recipe page show up in the saved recipes page. Something is incompatible in the spoonacular direction items and I cannot find out the solutions yet. 

2. Each user seems only be able to save one spoonacular recipe. The later saved one will overwrite the previous one in the saved recipes list.

### CODE REVIEW

**Comment by MaceeQi** [comment]
Thanks for implementing this feature, Yutong! All worked well aside from the points you mentioned.

**Comment by t1yena** [comment]
Thank you for implementing this Yutong!! I agree with you and macee- everything looks good except what you already mentioned

**Comment by nala-he** [comment]
Fixed all bugs mentioned above.

**Comment by MaceeQi** [comment]
Works great! One thing I noticed is that if I view the details of some spoonacular recipes from my saved recipes page, the directions section has html tags (for example can be seen in "Roasted Broccoli with Lemon and Garlic" recipe from search with ingredient of "broccoli")

**Comment by nala-he** [comment]
> broccoli

Fixed! Thank you!

**Comment by MaceeQi** [comment]
Works great now - thanks for making all the changes, Yutong! I think it's good to merge :)

**Pull request merged**
