### PR TITLE
Integration3 friends

### PR DESCRIPTION
**Pull request by nala-he**
Combined the friends feature with updated integration2 (after merging Yena's recipes details). 
1. Logged in user can follow author in home page. After clicking follow, they will be directed to the profile page and see the updated followings count on their profile page.
2. Logged in user can click following or follower to see their corresponding list of friends and access these friends' profile or recipes (if available). 
3. Friends' profile path and my-recipes path are different from logged in user's profile path and my-recipes path format.

Needs to update:
1. If you go to a friend's my-recipes page, you will see the logged in user's my-recipes list instead of the friends'. I am planning to create an additional friends-my-recipes page and have corresponding path link to it.

2. I removed the recipes count in the list of friends (following/followers) page, as it will use up resources and cause error massages if we calculate each friend's created recipes on the spot, unless we already have the count stored in users' data collection. I guess it is okay to remove this tiny feature so that we do not need to refactor all users' schema and fields.

3. I noticed an error message in console "GET http://localhost:4000/fridge/users//fridge-ingredients 404 (Not Found)", seems like the path for the fridge-ingredients got an extra "/". I haven't gotten the chance to locate which part is wrong. Let me know if you can spot it.

Please play around and let me know if you found any errors.

### CODE REVIEW

**Comment by MaceeQi** [comment]
Hi Yutong, I tried it out and was able to follow a user from the Home page and see the updated counts in both profiles (my profile and person I just followed's profile) like you mentioned. A few things I noticed:

1) I was not able to access a friend's MyRecipes page but it was because it seems like the MyRecipes component is going in an infinite loop. I end up having to close out of the site entirely because it freezes and crashes. The error I get is "Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render"

2) Right now we can only follow a user if they posted a recipe and we see it in the Home page. I think we had mentioned adding a Follow button in another user's profile, but if that's complicated to implement then I'm also okay with leaving it as it is

In response to your need to update points - I agree, we can remove the feature of displaying # of recipes in the Friends pages. Regarding the error message for fridge ingredients, that's because the useState is set to '' for the user ID while we retrieve the currently logged in user from the reducer. So it calls the thunk with '' before the currently logged in user is returned from the reducer, resulting in that error message. But once the current user is retrieved from the reducer, then it correctly retrieves the fridge ingredients for the user. The fridge ingredients should still work as expected aside from seeing this error message in the console. I just played around with it in the feature branch that I'm working on now and was able to avoid that initial call so I'll push that update once I'm done with the branch I'm working on!

**Comment by nala-he** [comment]
> Hi Yutong, I tried it out and was able to follow a user from the Home page and see the updated counts in both profiles (my profile and person I just followed's profile) like you mentioned. A few things I noticed:
> 
> 1. I was not able to access a friend's MyRecipes page but it was because it seems like the MyRecipes component is going in an infinite loop. I end up having to close out of the site entirely because it freezes and crashes. The error I get is "Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render"
> 2. Right now we can only follow a user if they posted a recipe and we see it in the Home page. I think we had mentioned adding a Follow button in another user's profile, but if that's complicated to implement then I'm also okay with leaving it as it is
> 
> In response to your need to update points - I agree, we can remove the feature of displaying # of recipes in the Friends pages. Regarding the error message for fridge ingredients, that's because the useState is set to '' for the user ID while we retrieve the currently logged in user from the reducer. So it calls the thunk with '' before the currently logged in user is returned from the reducer, resulting in that error message. But once the current user is retrieved from the reducer, then it correctly retrieves the fridge ingredients for the user. The fridge ingredients should still work as expected aside from seeing this error message in the console. I just played around with it in the feature branch that I'm working on now and was able to avoid that initial call so I'll push that update once I'm done with the branch I'm working on!

Thank you, Macee! I fixed the inifinte calling my-recipes issues by adding dependencies. I can add another following button in the profile page.

**Comment by t1yena** [comment]
Everything looks good to me except for what you already mentioned in #1 for needs to update in your comment!

**Comment by MaceeQi** [comment]
Hi Yutong, sorry for the delay. Agree with Yena - everything works great besides viewing the friend's MyRecipes page as you mentioned! I think we can merge for now

**Pull request merged**
