### PR TITLE
Integration2 login/signup

### PR DESCRIPTION
**Pull request by nala-he**
Bugs-free version based on my tests so far. 

New users can sign up (must fill out the required field). Old user from our database can login using username and password. Once logged in/signed up, users will be directed to their profile page and the profile path will not show the logged in users' ids. Users can edit their profiles and see the updates after clicking save button both on profile page and the MongoDB database. 

A few changes in fridge/index.js route path to differentiate currentUser's (i.e. logged in user) profile path and my recipes path from their friends' profile pages and recipes pages. 

I used users-reducer for the login/signup/profile info. The previously used profile-reducer was kept but not used at all.

You may not click the friends nav button or following/followers buttons now as they have not been implemented completely and will lead you to blank pages.

### CODE REVIEW

**Comment by MaceeQi** [comment]
For some reason I'm still not able to see the changes I make to my profile after clicking save. I can only see the change after I navigate away and then back to profile. Another thing that I'm not sure is supposed to be happening is that after I'm logged in, if I just reload the page it automatically kicks me out to the log in page and I can't go anywhere besides the Home page - it's like I'm logged out without even clicking the log out button. But I don't think I'm actually logged out because when I try to log in or sign up, I keep getting a 403 error.

**Comment by nala-he** [comment]
> For some reason I'm still not able to see the changes I make to my profile after clicking save. I can only see the change after I navigate away and then back to profile. Another thing that I'm not sure is supposed to be happening is that after I'm logged in, if I just reload the page it automatically kicks me out to the log in page and I can't go anywhere besides the Home page - it's like I'm logged out without even clicking the log out button. But I don't think I'm actually logged out because when I try to log in or sign up, I keep getting a 403 error.

I must have changed something while fixing other bugs and make it not working anymore. Not sure why. Went to the office hour and the TA could not find the reason. It seems that my updateUserThunk cannot take in the editedProfile as the variable and pass it to the reducer as payload object. But we don't know why and how to fix it now.

**Comment by nala-he** [comment]
Newest update. Magically fix the bug but not sure why/how I make it.

**Comment by MaceeQi** [comment]
Based on my tests, it works!! 😄 🎉  One very small change that I tried out and think would look nice - do you mind adding in "object-fit: cover;" to .wd-profile-avatar in components/profile/index.css? It will make the photo more proportional and less squished. Otherwise, I think it's good!

**Comment by nala-he** [comment]
> object-fit: cover

Updated according to Macee's suggestion

**Pull request merged**
