### PR TITLE
Integration3 update saved recipes

### PR DESCRIPTION
**Pull request by MaceeQi**
Changes made in this branch:

1) Removed the delete recipe buttons when viewing a friend's MyRecipes page. Now should only ever be able to delete your own recipes (previously could delete a friend's recipe if on their MyRecipes page)

2) Deleting one of your own recipes from the MyRecipes page will also delete any saved recipes associated to the recipe

3) Added extra check to ensure recipes returned from find saved recipes by user is associated to either a recipe from our database or spoonacular recipe, so deleting a recipe directly in mongo should not be a problem

### CODE REVIEW

**Review by nala-he — APPROVED** [review]
Hi Macee, thank you for the revisions! #1 and #2 worked as expected! For #3, I guess we will see how it works after combining with my thirdParty-saved-recipe branch, but I am able to delete both local recipe and spoonacular recipe from the saved-recipes database successfully. So we should be all good!

Just double-check, in this branch, when we click the saved-recipes button, it is supposed to crash, right?

**Comment by MaceeQi** [comment]
> Hi Macee, thank you for the revisions! #1 and #2 worked as expected! For #3, I guess we will see how it works after combining with my thirdParty-saved-recipe branch, but I am able to delete both local recipe and spoonacular recipe from the saved-recipes database successfully. So we should be all good!
> 
> Just double-check, in this branch, when we click the saved-recipes button, it is supposed to crash, right?

Which saved recipes button crashed? If I remember correctly, it would crash if the user has spoonacular recipes saved because the saved recipes with third party hadn't been merged in to this branch yet. I just merged your savedRecipes-thirdParty branch so I don't think anything should crash. If it still is, let me know - I'll have to look into it

**Comment by nala-he** [comment]
> > Hi Macee, thank you for the revisions! #1 and #2 worked as expected! For #3, I guess we will see how it works after combining with my thirdParty-saved-recipe branch, but I am able to delete both local recipe and spoonacular recipe from the saved-recipes database successfully. So we should be all good!
> > Just double-check, in this branch, when we click the saved-recipes button, it is supposed to crash, right?
> 
> Which saved recipes button crashed? If I remember correctly, it would crash if the user has spoonacular recipes saved because the saved recipes with third party hadn't been merged in to this branch yet. I just merged your savedRecipes-thirdParty branch so I don't think anything should crash. If it still is, let me know - I'll have to look into it

Just checked the updated version. All good to merge!!

**Review by t1yena — APPROVED** [review]
everything works on my end!!

**Pull request merged**
