### PR TITLE
Integration3 fix my recipes

### PR DESCRIPTION
**Pull request by nala-he**
Fixed issues in my-recipes list for both friends and current logged in users. Everything should be working now for profile, friends, my-recipes features.

### CODE REVIEW

**Comment by MaceeQi** [comment]
Hi Yutong, looks great! To clarify, when we view a friend's profile, if we click on the Friends tab in the nav bar, are we supposed to see the friend's friends? I noticed that is happening but just wanted to double check that that was on purpose

**Comment by MaceeQi** [comment]
One thing I noticed as I was playing around with it - when viewing recipe details from the MyRecipes page of a friend, when clicking on the save recipe button, it navigates the user to their own MyRecipes page which can be a little confusing. Should we change this to navigate to the user's saved recipes page? Or just back to the friend's MyRecipes page?

**Comment by nala-he** [comment]
> One thing I noticed as I was playing around with it - when viewing recipe details from the MyRecipes page of a friend, when clicking on the save recipe button, it navigates the user to their own MyRecipes page which can be a little confusing. Should we change this to navigate to the user's saved recipes page? Or just back to the friend's MyRecipes page?

Thank you! I changed it to navigate back to the logged in user's saved recipes page.

**Comment by nala-he** [comment]
> Hi Yutong, looks great! To clarify, when we view a friend's profile, if we click on the Friends tab in the nav bar, are we supposed to see the friend's friends? I noticed that is happening but just wanted to double check that that was on purpose

I did not notice that! I will see if I have time to fix it so that clicking friends only shows the logged-in user's friends. If I am running out of time, I guess we can leave it like this for now > U <

**Pull request merged**
