### PR TITLE
Integration2 recipe details

### PR DESCRIPTION
**Pull request by t1yena**
- implemented open recipe functionality
- modified recipe details &create recipe to take in image URLs and render them properly. 
- implemented my recipes & my recipe details, no more hard coding. 
- All buttons should now work without any issues. 

todo:
- still need to add ingredients and directions to recipe details but I want you guys to try it out first to make sure everything is working properly. If everything works, we can merge it first so we can move forward with other features and ill make a separate branch for adding ingredients and directions to recipe details.

### CODE REVIEW

**Comment by nala-he** [comment]
Hi Yena, all buttons work as expected! The created recipes are listed in my recipes and home page as expected with currently implemented detail info.

I noticed a few things related to the recipe images:
1. When I went to create recipes screen, the image is originally the default one, then after a few seconds to one minute, the image will be changed to the ice-cream image. (probably the last created recipe used the ice-cream image?) It is not always like that, though. If you did not observe the same think, you may ignore this.

2. After I created a new recipe, the avatar image of the new created recipe in the list of my recipes is not showing. It is just showing the alt info.

3. After creating a recipe with an url image, if I create the second recipe leaving the image URL field blank, the second recipes will have the previously created recipe's image automatically.

**Comment by MaceeQi** [comment]
A few things I noticed:

1) Same as Yutong's third point - if I do not add a recipe URL when I create a recipe, it assigns the previously created recipe's image to the recipe rather than the default one

2) Didn't realize this until now but it seems like when the front end portion was implemented for each recipe post, it was set to a specific size so if the intro is long, the outer components will not stretch to fit it, causing an overflow

3) Also noticed that when you open the recipe from the home page, the details page doesn't have any buttons. Not sure if this was intentional or not?

4) Under the My Recipes page, the recipe pics are not loading. I think it's probably because the code is still set to look for images in our project rather than url image so that will probably need to be updated now that we're using image URLs

Otherwise, everything else works as you mentioned!

**Comment by t1yena** [comment]
todo for yena for next feature branch:

- add save recipe button for recipe details from home page
- add ingredients and directions to recipe details
- add privacy for recipe details
- don't show create recipe button for no recipe creators

**Comment by MaceeQi** [comment]
Works great now after the updates - thank you for changing!

**Review by nala-he — APPROVED** [review]
Thank you for the changes! All good!! 
Sorry for not pointing it out earlier, I noticed that the "open recipes" button in the home page is not aligned with other two buttons. We can fix it in the next integration branch later.

**Pull request merged**
