### PR TITLE
Integration2 recipes

### PR DESCRIPTION
**Pull request by t1yena**
connected recipes, recipe ingredients, and recipe directions front end & backend. Also created a temp new nav bar to enable onClick for create recipes.

### CODE REVIEW

**Comment by MaceeQi** [comment]
Not sure if I'm just not running it correctly, but when I go to create a recipe, clicking on Add Ingredient and Add Direction buttons don't seem to do anything. 

Besides that, when the user clicks Save Recipe after creating their recipe, I think it would be nice if the page navigated to the MyRecipes page or somewhere else to indicate that the recipe was saved.

**Review by nala-he — COMMENTED** [review]
Hi Yena, I can successfully create recipes and find it in our remote database. 

A few questions on the current feature (we might have discussed them but I forgot. > U <): 1) I am not sure if I should be able to see my newly created recipe listed in the home page. I could not tell as my recipe name ("raw potato") or description were not there. 2) Will users be able to click the recipe on the home page and see the recipe details? Or will they just follow and save recipes without actually looking into the recipe contents? 

Two suggestions: 1) Maybe we can change the file input for recipe image into URL text input so the page can actually render the image the user choose online. Otherwise, without a cloud storage for storing the images, we will just have user's image names stored, rather than the image itself. I implemented the image update feature in edit-profile page so that the user can type in nothing with our default emptyPortrait rendered, typing in the image link url online, or use the image name in our image directory. If you want to make the change, you may want to take a look at the edit-profile.js. But I guess keeping it as original way is also fine. 
2) Do you mind adding the measurement units after the input fields for nutrition component? I typed in "100 cal" for calories and crashed the server because it is supposed to take Number type instead of String. Or you may just want to change calories type to String in the recipes-schema. 

Sorry for such long paragraphs. Just some thoughts rushed into my mind. Thank you!!

**Comment by MaceeQi** [comment]
Now that I'm running the project with the correct Node branch, the Add Ingredient/Add Direction buttons work well! 

I think Yutong brings up some good questions / suggestions. One small change that I think would be nice is when creating a recipe, maybe adding the recipe to the beginning of the array rather than the end is better so that the newest recipes are at the top when you're in the Home page. Another thing I noticed is that sometimes some empty recipes are added to the database and when that happens, we have empty recipes showing up in the Home page. I also noticed that when I am under the Create Recipe tab and I refresh the screen, it crashes. I think this is one source of where the empty recipes are originating from. Another source is when I click on the Create Recipe tab and then navigate to a different tab (without clicking cancel), I think an empty recipe is again created but not deleted.

**Comment by MaceeQi** [comment]
Tried creating a recipe and it works well now! Two things I'm not sure whether you were planning on changing later but I think will eventually need to be updated: 

1) As Yutong mentioned in an earlier comment, not sure if you were going to change the file input into URL text input instead as she suggested but the recipe pictures I upload are not displaying when we use the Choose File from computer feature
2) Regular users are still able to access the Create Recipe button - I think we should hide this feature for regular users

Besides those, I think it's working great now! Thanks for the changes!

**Pull request merged**
