### PR TITLE
Integration3 recipes

### PR DESCRIPTION
**Pull request by t1yena**
completed more recipe stuff

- recipe details now show ingredients and directions
- added save recipe button for recipe details
- added privacy input field to create recipes
- only shows create recipe button in nav bar to non average users

### CODE REVIEW

**Review by nala-he — APPROVED** [review]
I think it's good to merge. Once we combine this feature branch with my updated friends branch, we can continue to debug and revise. Currently, when I click save recipe button in a detail page, it will kick me out of login status.

**Comment by MaceeQi** [comment]
Hi Yena, sorry for the delay. I think it looks great! One thing I noticed is that when I create a private recipe, it's still listed as public when I look at the MyRecipes page and I can still see it in the Home page if I log in as a different user

**Comment by t1yena** [comment]
my bad!! ill fix that

**Review by nala-he — COMMENTED** [review]
The privacy feature works well! I noticed that when I open a recipe from my-recipes page, the node server crashed. (CastError: Cast to ObjectId failed for value "my-recipes" (type string) at path "rid" for model "RecipeIngredientsModel")

**Comment by MaceeQi** [comment]
Thanks for the updates, Yena! Privacy works well! One thing I did notice is that if I view a user I'm following's MyRecipes page, it only shows their public recipes even though I am following them. Also, I did run into a similar issue as Yutong where opening the recipe details from a MyRecipes page crashes the server

**Comment by MaceeQi** [comment]
Thank you for the changes, Yena! I noticed a few things as I was playing around with it:

1) For some reason, if I navigate to a friend's MyRecipes page through their profile and then click on the MyRecipes tab from there, it still only shows their public recipes. But it works (shows public and private recipes) if I navigate directly to their MyRecipes page by clicking on the Recipes button in the friends list rather than the profile button

2) Clicking the logout button when I am in the MyRecipes page (for friend and/or currently logged in user) will cause the page to crash with the error "Uncaught TypeError: Cannot read properties of null (reading '_id') at MyRecipes"

3) Also a small detail, but the three pink buttons (Save Recipe, Follow Author, and Close) that were added to the bottom of the recipe details when you click open recipe from the home page seems to also be showing up in MyRecipes details and SavedRecipes details which already have close and save recipe buttons so it can be a little repetitive. I think it might be because the buttons were added to a component that is being reused across the app

These are all pretty small details so if we don't have time, I think it'll be okay. But definitely wanted to point out #1 and #2 for the demo in case we don't fix it!

**Comment by nala-he** [comment]
> Thank you for the changes, Yena! I noticed a few things as I was playing around with it:
> 
> 1. For some reason, if I navigate to a friend's MyRecipes page through their profile and then click on the MyRecipes tab from there, it still only shows their public recipes. But it works (shows public and private recipes) if I navigate directly to their MyRecipes page by clicking on the Recipes button in the friends list rather than the profile button
> 2. Clicking the logout button when I am in the MyRecipes page (for friend and/or currently logged in user) will cause the page to crash with the error "Uncaught TypeError: Cannot read properties of null (reading '_id') at MyRecipes"
> 3. Also a small detail, but the three pink buttons (Save Recipe, Follow Author, and Close) that were added to the bottom of the recipe details when you click open recipe from the home page seems to also be showing up in MyRecipes details and SavedRecipes details which already have close and save recipe buttons so it can be a little repetitive. I think it might be because the buttons were added to a component that is being reused across the app
> 
> These are all pretty small details so if we don't have time, I think it'll be okay. But definitely wanted to point out #1 and #2 for the demo in case we don't fix it!

For #2, I managed to solve it by adding if (currentUser) to the useEffect function and change the currentUser._id to currentUser in the dependency array.

**Comment by MaceeQi** [comment]
Works great now, thanks yena!! I think it's good to merge :)

**Pull request merged**
